version: '3.1'
services:
  app:
    container_name: app-eleicoes
    image: app-eleicoes
    build: ./eleicaoapi/
    ports:
      - "8889:8080"
    depends_on:
      - dbpostgresql
    links:
      - "db:database"
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=eleicoes